site_name: sofastats
repo_url: https://github.com/grantps/sofastats_lib/
site_description: Documentation for sofastats_lib
nav:
  - README: 'README.md'
  - Output Gallery: 'output_gallery.md'
  - API: 'API.md'
  - Styles: 'styles.md'
  - Data Preparation: 'data_prep.md'
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_signature_annotations: true
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
  logo: images/bunny_head_small.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-6
        name: Switch between light and dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: #3465a4;
      scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: #3465a4;
      scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
extra_css:
    - stylesheets/extra.css
